// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject_WP
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertMethod1 - Use 'AssertMethod1ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            XamlControl uIScrollViewerPane = this.UIParserAppWindowsPhonWindow.UIScrollViewerPane;
            #endregion

            // Verify that the 'Enabled' property of 'scrollViewer' pane equals 'True'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIScrollViewerPaneEnabled, uIScrollViewerPane.Enabled, "Error");
        }
        
        #region Properties
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public UIParserAppWindowsPhonWindow UIParserAppWindowsPhonWindow
        {
            get
            {
                if ((this.mUIParserAppWindowsPhonWindow == null))
                {
                    this.mUIParserAppWindowsPhonWindow = new UIParserAppWindowsPhonWindow();
                }
                return this.mUIParserAppWindowsPhonWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private UIParserAppWindowsPhonWindow mUIParserAppWindowsPhonWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Enabled' property of 'scrollViewer' pane equals 'True'
        /// </summary>
        public bool UIScrollViewerPaneEnabled = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIParserAppWindowsPhonWindow : XamlWindow
    {
        
        public UIParserAppWindowsPhonWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "ParserApp.WindowsPhone";
            #endregion
        }
        
        #region Properties
        public XamlControl UIScrollViewerPane
        {
            get
            {
                if ((this.mUIScrollViewerPane == null))
                {
                    this.mUIScrollViewerPane = new XamlControl(this);
                    #region Search Criteria
                    this.mUIScrollViewerPane.SearchProperties[UITestControl.PropertyNames.ControlType] = "Pane";
                    this.mUIScrollViewerPane.SearchProperties[UITestControl.PropertyNames.ClassName] = "ScrollViewer";
                    this.mUIScrollViewerPane.SearchProperties["AutomationId"] = "scrollViewer";
                    #endregion
                }
                return this.mUIScrollViewerPane;
            }
        }
        #endregion
        
        #region Fields
        private XamlControl mUIScrollViewerPane;
        #endregion
    }
}
