insert all
into **** values(01,'Aguascalientes')
into **** values(02,'Baja California')
into **** values(03,'Baja California Sur')
into **** values(04,'Campeche')
into **** values(05,'Coahuila de Zaragoza')
into **** values(06,'Colima')
into **** values(07,'Chiapas')
into **** values(08,'Chihuahua')
into **** values(09,'Distrito Federal')
into **** values(10,'Durango')
into **** values(11,'Guanajuato')
into **** values(12,'Guerrero')
into **** values(13,'Hidalgo')
into **** values(14,'Jalisco')
into **** values(15,'México')
into **** values(16,'Michoacán de Ocampo')
into **** values(17,'Morelos')
into **** values(18,'Nayarit')
into **** values(19,'Nuevo León')
into **** values(20,'Oaxaca')
into **** values(21,'Puebla')
into **** values(22,'Querétaro')
into **** values(23,'Quintana Roo')
into **** values(24,'San Luis Potosí')
into **** values(25,'Sinaloa')
into **** values(26,'Sonora')
into **** values(27,'Tabasco')
into **** values(28,'Tamaulipas')
into **** values(29,'Tlaxcala')
into **** values(30,'Veracruz de Ignacio de la Llave')
into **** values(31,'Yucatán')
into **** values(32,'Zacatecas')
select * from dual;
commit;
